services:
  postgres:
    image: postgres:16
    container_name: rental-marketplace
    environment:
      POSTGRES_DB: rental_marketplace
      POSTGRES_USER: marketplace_admin
      POSTGRES_PASSWORD: Qz7mPk2xVr9L
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace_admin -d rental_marketplace"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

